
version: "3"
services:
  # docker:
  #   container_name: docker
  #   image: docker:latest
  #   command: docker run --rm --network postgres
  #   networks:
  #     - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
      # - G:\docker-family\syc\postgres:/var/lib/postgresql/data
      # - /data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ${PGADMIN_DATA_DIR}:/var/lib/pgadmin
      # - G:\docker-family\syc\pgadmin:/var/lib/pgadmin
      # - /data/pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - postgres
  
  # main:
  #   container_name: main
  #   build:
  #     context: .
  #   env_file:
  #     - docker.env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #   - 8001:8001
  #   - 9229:9229
  #   command: npm run start:dev
  #   depends_on:
  #     - postgres
  #   restart: always
  #   networks:
  #     - postgres

networks:
  postgres:
    driver: bridge
